### ISSUE TITLE
The generation of data under m_learning, scikit 

### ISSUE THREAD

**Issue by gyb1325** [mondejar/ecg-classification#1]
In your python version, it read the data under the scikit folder. However, there is no mention about how to generate these data. Did I miss something?

**Comment by mondejar** [comment]
Check the section "About Dataset" from the Readme. There are the steps to download the original dataset from physionet and convert to .csv files. Additionally, I put a link to download the dataset formatted as .csv files exactly as I employed: kaggle.com/mondejar/mitbih-database

**Comment by gemorningsun** [comment]
> In your python version, it read the data under the scikit folder. However, there is no mention about how to generate these data. Did I miss something?
hello！ I have the same confusion. Did you solve it ？
