### ISSUE TITLE
Module cPickle is missing. 

### ISSUE THREAD

**Issue by GrayLand119** [mondejar/ecg-classification#2]
I can't find the `cPickle` module in project, and I searching `cPickle` In Project, got the result below:
![image](https://user-images.githubusercontent.com/11648047/43876200-8e244e26-9bc6-11e8-899f-2e19dfc59912.png)

**Comment by lehoangthanh1809** [comment]
cPickle is a python's library. You can install it via pip.

**Comment by TaeJoongYoon** [comment]
Use _pickle instead of cPickle.

cPickle is not supported in Python3.x.

**Comment by GrayLand119** [comment]
Thanks @TaeJoongYoon !~ 
I use`_pickle` to instead, It does work.
