### ISSUE TITLE
Improve Results

### ISSUE THREAD

**Issue by banivyom** [mondejar/ecg-classification#6]
Right now I'm using single SVM with C_value = {0.001, 0.01, 0.1, 1, 10, 100} and oversampling(SMOTE) the train data, gamma_value=0.0 but the sensitivity for S and F class is very low. I read your paper and it says that Ensemble of SVMs with product rule will give good results. Can you please suggest any resources that I can use to implement this in python as I'm finding it difficult?
Best result obtained till now:
Ijk: 0.5552
Ij: 2.2895
Cohen's Kappa: 0.5380

Confusion Matrix:

[39988  1621   821  1603]
[902 693 434  21]
[ 113   16 3088    3]
[249   1 102  36]

Overall ACC: 0.8815

mean Acc: 0.9408
mean Recall: 0.5745
mean Precision: 0.4959
N:

Sens: 0.9081
Prec: 0.9694
Acc: 0.8932
SVEB:

Sens: 0.3380
Prec: 0.2973
Acc: 0.9397
VEB:

Sens: 0.9590
Prec: 0.6952
Acc: 0.9701
F:

Sens: 0.0928
Prec: 0.0216
Acc: 0.9602

**Comment by mondejar** [comment]
Check the file /python/basic_fusion.py of this repository. In order to run the ensemble you have to train and run several SVM models, each one with a different feature, and then combine their decisions with this code.

**Comment by banivyom** [comment]
One more and the last thing left is to implement SVM+PSO. Can you provide some resources I can take make use of, because as of now I learned about pyswarms library but unable to go further with this..
Any tiny help will be appreciated sir.
