### ISSUE TITLE
No data for 'Q' Class 

### ISSUE THREAD

**Issue by banivyom** [mondejar/ecg-classification#7]
When I delete all pickle files and then edit the load_MITBIH.py to include the fifth(Q) class, only 4 classes get included and not the fifth. I have also updated the evaluation_AAMI.py for confusion matrix for 5 class, but fifth row and column contains 0 always.
I'm taking window size of 180 centred at R-peak.

What should I do?

**Comment by mondejar** [comment]
Check carefully if there are instances labelled with Q class in each dataset. Due to the window size and the database division, it's possible that no Q samples are being used during training.
